name: ClashForge

on:
  workflow_dispatch:

jobs:
  run_demo_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      - name: Install requirements.txt
        run: |
          pip install -r ./requirements.txt

      - name: Run ClashForge.py
        run: |
          python ClashForge.py
          mkdir dist
          cp ./clash_config.yaml ./dist/

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: release
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
